# NumPy Review


We might use numpy occasionally in this course. Here is a quick review of some common numpy functions and operations.

In [15]:
import numpy as np



In [16]:
# Creating an array and checking its shape
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:", arr)
print("Shape of the array:", arr.shape)



Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)


In [17]:
# Creating Special Arrays
zeros = np.zeros((2, 3))
print("Zeros Array:", zeros)

ones = np.ones((3, 2))
print("Ones Array:", ones)


Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# Generating Random Numbers
randint_arr = np.random.randint(0, 10, size=(2, 3))
print("Random Integer Array (0-9):", randint_arr)

rand_arr = np.random.rand(2, 3)
print("Random Float Array (0-1):", rand_arr)



Random Integer Array (0-9): [[0 7 6]
 [9 4 5]]
Random Float Array (0-1): [[0.1068836  0.37113198 0.13798259]
 [0.14274836 0.70673626 0.98148006]]


In [19]:
# Indexing and Slicing
# Similar to python lists
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

print("Element at row 0, column 1:", arr[0, 1])
print("First row:", arr[0, :])
print("First column:", arr[:, 0])

# last row
print("Last row:", arr[-1, :])

# subarray 0th and 1st row, 1st and 2nd column
# the start index is inclusive and end index is exclusive
print("Subarray:", arr[0:2, 1:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
First row: [1 2 3]
First column: [1 4 7]
Last row: [7 8 9]
Subarray: [[2 3]
 [5 6]]


In [20]:
# Element-wise Operations
print("\nElement-wise Operations:")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# Scalar Operations
scalar = 5
print("add each elem by the scalar", arr + scalar)


Element-wise Operations:
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
add each elem by the scalar [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [21]:
# Common Functions
print("\nCommon Functions:")
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))


Common Functions:
Mean: 5.0
Sum: 45
Max: 9


In [22]:
# Common functions along axes
print("Mean along rows (axis=1):", np.mean(arr, axis=1))
print("Mean along columns (axis=0):", np.mean(arr, axis=0))

Mean along rows (axis=1): [2. 5. 8.]
Mean along columns (axis=0): [4. 5. 6.]


In [23]:
# Reshaping Arrays
reshaped_arr = arr.reshape(1, 9)
print("Reshaped Array:", reshaped_arr)

Reshaped Array: [[1 2 3 4 5 6 7 8 9]]


In [24]:
# Boolean Indexing
print("Array > 5 gives:", arr > 5)
print("Elements greater than 5:", arr[arr > 5])
print("Sum of True values (treating True as 1, False as 0):", np.sum(arr > 5))

Array > 5 gives: [[False False False]
 [False False  True]
 [ True  True  True]]
Elements greater than 5: [6 7 8 9]
Sum of True values (treating True as 1, False as 0): 4
